name: check

on: pull_request

jobs:
  seocheck:
    name: Markdown SEO Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Markdown SEO Check
        uses: zentered/markdown-seo-check@v1.1.0
        with:
          max_title_length: 70
          max_slug_length:
          max_description_length: 150
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
